### ISSUE TITLE
Exceptions: add row number in message

### ISSUE THREAD

**Issue by tiohlognm** [kniazkov/goat#47]
Row number is helpful.
```
goat program.goat 
unhandled exception: operator '+' not found
```

**Comment by kniazkov** [comment]
Consider this code:
```
var f = $() {
    undefined.toString();
};

f();
```
This code will cause an exception:
```
unhandled exception: '"toString"' is not a method
```
Now start the interpreter with --debug and --run keys. The interpreter will start in the debug mode. In this mode, the extending debug abilities supported, including stack tracing. The output will be like this:
```
./goat program.goat --debug --run
unhandled exception: '"toString"' is not a method
  program.goat, 2.5
  program.goat, 5.1
```
Hope this helps.
How do you think should we document this feature?

**Comment by kniazkov** [comment]
Could we close the issue?
