### ISSUE TITLE
Debug mode: suggestion: make setting breakpoint command shorter

### ISSUE THREAD

**Issue by tiohlognm** [kniazkov/goat#50]
Now it's:
```
./goat.exe program.goat --debug
? b program.goat : 21
setting breakpoint at program.goat, 21
```

We've already know that we in program.goat, it's not necessary to specify the file name. 
Could we skip it if there is only one file on program?

**Comment by kniazkov** [comment]
Done
Please re-build the interpreter. The syntax is:
```
./goat.exe program.goat --debug
? b  21
setting breakpoint at program.goat, 21
```
This command inserts a breakpoint to the main file (name specified as a parameter of the interpreter).

**Comment by tiohlognm** [comment]
amazing
